name: Static Code Security Analysis

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: "Branch or ref that triggered the scan"
      default_branch:
        type: string
        required: true
        description: "Default branch of the repository"
      push_before_sha:
        type: string
      push_base_sha:
        type: string
      pull_base_sha:
        type: string
    secrets:
      gitguardian_api_key:
        required: true
        description: "GitGuardian API key"
      snyk_token:
        required: false
        description: "Snyk token"

jobs:
  code_security:
    name: Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: GitGuardian - Secrets Detection
        uses: GitGuardian/ggshield/actions/secret@v1.37.0
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.gitguardian_api_key }}
          GITHUB_PUSH_BEFORE_SHA: ${{ inputs.push_before_sha }}
          GITHUB_PUSH_BASE_SHA: ${{ inputs.push_base_sha }}
          GITHUB_PULL_BASE_SHA: ${{ inputs.pull_base_sha }}
          GITHUB_DEFAULT_BRANCH: ${{ inputs.default_branch }}

      - name: Snyk - Dependency Vulnerability Check
        uses: snyk/actions@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        with:
          command: test
        continue-on-error: true
