name: Deploy to Vercel

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "The environment of the deployment"
        required: true
        default: "unknown"
      vercel_org_id_ref:
        type: string
        description: The reference to the Vercel organization ID
        required: true
      vercel_project_id_ref:
        type: string
        description: The reference to the Vercel project ID
        required: true
      vercel_token_ref:
        type: string
        description: The reference to the Vercel token
        required: true
    outputs:
      status:
        description: The status of the deployment
        value: ${{ jobs.deploy.outputs.status }}
      url:
        description: The URL of the deployment
        value: ${{ jobs.deploy.outputs.url }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: The 1Password service account token
        required: true

jobs:
  deploy:
    name: ${{ inputs.environment }}
    outputs:
      status: ${{ steps.deployment_status.outputs.result }}
      url: ${{ steps.deployment.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2.0.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          VERCEL_TOKEN: ${{ inputs.vercel_token_ref }}
          VERCEL_ORG_ID: ${{ inputs.vercel_org_id_ref }}
          VERCEL_PROJECT_ID: ${{ inputs.vercel_project_id_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install PNPM
        run: npm install --global pnpm@latest

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Cache pnpm store
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build Project Artifacts
        run: vercel build ${{ inputs.environment == 'production' && '--prod' || '' }} --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: deployment
        run: |
          DEPLOY_CMD="vercel --token=${{ env.VERCEL_TOKEN }} --confirm"
          [[ '${{ inputs.environment }}' == 'production' ]] && DEPLOY_CMD+=" --prod"
          DEPLOY_OUTPUT=$($DEPLOY_CMD)
          DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep -oE "https?://[a-zA-Z0-9./_-]+")
          echo "$DEPLOY_OUTPUT"
          echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Set Deployment Status Output
        id: deployment_status
        if: always()
        run: echo "result=${{ steps.deployment.outcome }}" >> $GITHUB_OUTPUT
