name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Deployment environment (e.g. production, preview)"
        required: true
      short_sha:
        type: string
      docker_image:
        type: string
        required: true
        description: "Image name without tag and owner (e.g., my-api)"
    secrets:
      KUBECONFIG:
        description: Base64-encoded kubeconfig file
        required: true
      K8S_SECRET:
        description: Base64-encoded Kubernetes secret YAML
        required: true
    outputs:
      status:
        description: The status of the deployment
        value: ${{ jobs.deploy.outputs.status }}

jobs:
  deploy:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.deployment_status.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kubernetes Config and Secret
        working-directory: k8s
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          echo "${{ secrets.K8S_SECRET }}" | base64 -d > secret.yaml

      - name: Install Kustomize
        working-directory: k8s
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - name: Set Docker Image in Kustomize
        working-directory: k8s
        run: |
          IMAGE_TAG="${{ inputs.short_sha && format('sha-{0}', inputs.short_sha) || 'latest' }}"
          kustomize edit set image "${{ secrets.DOCKER_USERNAME }}/${{ inputs.docker_image }}=${{ secrets.DOCKER_USERNAME }}/${{ inputs.docker_image }}:$IMAGE_TAG"

      - name: Apply Kubernetes Manifests
        id: deployment
        working-directory: k8s
        run: |
          kustomize build . | kubectl apply -f -
        continue-on-error: true

      - name: Set Deployment Status Output
        id: deployment_status
        if: always()
        run: echo "result=${{ steps.deployment.outcome }}" >> $GITHUB_OUTPUT
