name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "The environment of the deployment"
        required: false
        default: "unknown"
      secret_ref:
        type: string
        description: The reference to the Kubernetes secret
        required: true
      kubeconfig_ref:
        type: string
        description: The reference to the Kubernetes configuration
        required: true
    outputs:
      status:
        description: The status of the deployment
        value: ${{ jobs.deploy.outputs.status }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: The 1Password service account token
        required: true

jobs:
  deploy:
    name: ${{ inputs.environment }}
    outputs:
      status: ${{ steps.deployment_status.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1.0.0

      - name: Prepare Secrets
        working-directory: k8s
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: ${{ inputs.secret_ref }}
        run: |
          op read "$SECRET" | base64 --decode > secret.yaml

      - name: Install Kustomize
        working-directory: k8s
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - name: Set Docker Image in Kustomize
        working-directory: k8s
        run: |
          kustomize edit set image "${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}=${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}"

      - name: Configure Kubernetes Access
        working-directory: k8s
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          KUBECONFIG: ${{ inputs.kubeconfig_ref }}
        run: |
          mkdir -p ~/.kube
          op read "$KUBECONFIG" | base64 --decode > ~/.kube/config

      - name: Apply Kubernetes Manifests
        id: deployment
        working-directory: k8s
        run: |
          kustomize build . | kubectl apply -f -
        continue-on-error: true

      - name: Set Deployment Status Output
        id: deployment_status
        if: always()
        run: echo "result=${{ steps.deployment.outcome }}" >> $GITHUB_OUTPUT
