name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      STAGE:
        type: string
        description: The stage to deploy to
        required: true
        default: production
      SECRET_REF:
        type: string
        description: The reference to the Kubernetes secret
        required: false
        default: op://kubernetes/${{ github.event.repository.name }}/${{ inputs.STAGE }}
      KUBECONFIG_REF:
        type: string
        description: The reference to the Kubernetes configuration
        required: false
        default: op://kubernetes/kubeconfig/${{ inputs.STAGE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kustomize
        working-directory: k8s
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - name: Prepare Secrets
        working-directory: k8s
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: ${{ inputs.SECRET_REF }}
        run: |
          op read "$SECRET" | base64 --decode > secret.yaml

      - name: Set Docker Image in Kustomize
        working-directory: k8s
        run: |
          kustomize edit set image "${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}=${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}"

      - name: Configure Kubernetes Access
        working-directory: k8s
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          KUBECONFIG: ${{ inputs.KUBECONFIG_REF }}
        run: |
          mkdir -p ~/.kube
          op read "$KUBECONFIG" | base64 --decode > ~/.kube/config

      - name: Apply Kubernetes Manifests
        working-directory: k8s
        run: |
          kustomize build . | kubectl apply -f -
