name: Notify PR to Discord

on:
  workflow_call:
    inputs:
      DISCORD_WEBHOOK_REF:
        type: string
        description: 'The reference to the Discord webhook'
        required: true

jobs:
  notify:
    name: Discord
    runs-on: ubuntu-latest
    steps:
      - name: Load deployment secrets from 1Password
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DISCORD_WEBHOOK: ${{ inputs.DISCORD_WEBHOOK_REF }}

      - name: Send Discord notification
        uses: cabrera-evil/discord-notify-action@1.0.2
        with:
          webhook_url: ${{ env.DISCORD_WEBHOOK }}
          title: "PR notification: ${{ github.event.repository.name }}"
          description: |
            **Status:** ${{ github.event.pull_request.state }}
            **Issue:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
          include_image: true
          title_url: ${{ github.event.pull_request.html_url }}
