name: Notify Status to Discord
on:
  workflow_call:
    inputs:
      DISCORD_WEBHOOK_REF:
        type: string
        description: "The reference to the Discord webhook"
        required: true

jobs:
  notify:
    name: Discord
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DISCORD_WEBHOOK: ${{ inputs.DISCORD_WEBHOOK_REF}}

      - name: Set Notification Variables
        id: notification_vars
        if: always()
        run: |-
          case "${{ job.status }}" in
            success) echo "color=#17C964" >> $GITHUB_OUTPUT ;;
            failure) echo "color=#F31260" >> $GITHUB_OUTPUT ;;
            *)       echo "color=#FFA500" >> $GITHUB_OUTPUT ;;
          esac

      - name: Notify Discord
        if: always()
        uses: cabrera-evil/discord-notify-action@1.0.2
        with:
          webhook_url: ${{ env.DISCORD_WEBHOOK }}
          title: "Deployment notification: ${{ github.event.repository.name }}"
          description: |
            **Status:** ${{ job.status }}
            **Author:** ${{ github.actor }}
          color: "${{ steps.notification_vars.outputs.color }}"
          include_image: "true"
          title_url: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
