name: Notify Status to Discord
on:
  workflow_call:
    inputs:
      TITLE:
        type: string
        description: "The title of the deployment"
        default: "Deployment"
      DESCRIPTION:
        type: string
        description: "The description of the deployment"
        default: "A new deployment has been triggered"
      DISCORD_WEBHOOK_REF:
        type: string
        description: "The reference to the Discord webhook"
        required: true
      DEPLOY_STATUS:
        type: string
        description: "The status of the deployment"
        default: "unknown"
      DEPLOY_ENVIRONMENT:
        type: string
        description: "The environment of the deployment"
        default: "unknown"
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: The 1Password service account token
        required: true

jobs:
  notify:
    name: Discord
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DISCORD_WEBHOOK: ${{ inputs.DISCORD_WEBHOOK_REF}}

      - name: Set Environment
        id: set_environment
        run: |
          # Set notification color based on DEPLOY_STATUS
          case "${{ inputs.DEPLOY_STATUS }}" in
            success) echo "color=#17C964" >> $GITHUB_OUTPUT ;;
            failure) echo "color=#F31260" >> $GITHUB_OUTPUT ;;
            *)       echo "color=#FFA500" >> $GITHUB_OUTPUT ;;
          esac
          # Get git short SHA
          echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Notify Discord
        uses: cabrera-evil/discord-notify-action@1.1.7
        with:
          webhook_url: ${{ env.DISCORD_WEBHOOK }}
          title: "${{ inputs.TITLE }} notification: ${{ github.event.repository.name }}"
          description: "${{ inputs.DESCRIPTION }}"
          color: "${{ steps.set_environment.outputs.color }}"
          status: "${{ inputs.DEPLOY_STATUS }}"
          environment: "${{ inputs.DEPLOY_ENVIRONMENT }}"
          repo_name: "${{ github.event.repository.name }}"
          repo_url: "${{ github.event.repository.html_url }}"
          commit_message: "${{ github.event.head_commit.message }}"
          commit_sha: "${{ steps.set_environment.outputs.short_sha }}"
          author: "${{ github.actor }}"
          include_image: true
