name: Notify Status to Discord
on:
  workflow_call:
    inputs:
      title:
        type: string
        description: "The title of the deployment"
        required: false
        default: "Deployment"
      description:
        type: string
        description: "The description of the deployment"
        required: false
        default: "A new deployment has been triggered"
      webhook_ref:
        type: string
        description: "The reference to the Discord webhook"
        required: true
      status:
        type: string
        description: "The status of the deployment"
        required: false
        default: "unknown"
      environment:
        type: string
        description: "The environment of the deployment"
        required: false
        default: "unknown"
      url:
        type: string
        description: "The URL of the deployment"
        required: false
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: The 1Password service account token
        required: true

jobs:
  notify:
    name: Discord
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2.0.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DISCORD_WEBHOOK: ${{ inputs.webhook_ref}}

      - name: Set Environment
        id: set_environment
        run: |
          # Set notification color based on status
          case "${{ inputs.status }}" in
            success) echo "color=#17C964" >> $GITHUB_OUTPUT ;;
            failure) echo "color=#F31260" >> $GITHUB_OUTPUT ;;
            *)       echo "color=#FFA500" >> $GITHUB_OUTPUT ;;
          esac
          # Get git short SHA
          case "${{ github.event_name }}" in
            pull_request)
              echo "short_sha=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Notify Discord
        uses: cabrera-evil/discord-notify-action@1.1.8
        with:
          webhook_url: ${{ env.DISCORD_WEBHOOK }}
          title: "${{ inputs.title }} notification: ${{ github.event.repository.name }}"
          description: "${{ inputs.description }}"
          color: "${{ steps.set_environment.outputs.color }}"
          status: "${{ inputs.status }}"
          environment: "${{ inputs.environment }}"
          url: "${{ inputs.url }}"
          repo_name: "${{ github.event.repository.name }}"
          repo_url: "${{ github.event.repository.html_url }}"
          commit_message: "${{ github.event.head_commit.message }}"
          commit_sha: "${{ steps.set_environment.outputs.short_sha }}"
          author: "${{ github.actor }}"
          include_image: true
