name: Publish to NPM

on:
  workflow_call:
    inputs:
      npm_token_ref:
        type: string
        description: The reference to the NPM token
        required: true
    outputs:
      status:
        description: The status of the deployment
        value: ${{ jobs.publish.outputs.status }}
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: The 1Password service account token
        required: true

jobs:
  publish:
    name: NPM
    outputs:
      status: ${{ steps.publish_status.outputs.status }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2.0.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          NPM_TOKEN: ${{ inputs.npm_token_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install PNPM
        run: npm install --global pnpm@latest

      - name: Cache pnpm store
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build package
        run: pnpm build

      - name: Publish to NPM registry
        id: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{env.NPM_TOKEN}}
        continue-on-error: true

      - name: Set Publish Status Output
        id: publish_status
        if: always()
        run: echo "result=${{ steps.publish.outcome }}" >> $GITHUB_OUTPUT
