name: Set Environment
on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: 'The branch to deploy'
        required: true
    outputs:
      environment:
        description: 'The deployment environment'
        value: ${{ jobs.set_environment.outputs.environment }}

jobs:
  set_environment:
    name: Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_environment.outputs.environment }}
    steps:
      - name: Checkout
        id: set_environment
        run: |-
          # Set deployment environment based on branch
          case ${{ inputs.ref }} in
            refs/heads/master|refs/heads/main)
              echo "environment=production" >> $GITHUB_OUTPUT ;;
            *)
              echo "environment=preview" >> $GITHUB_OUTPUT ;;
          esac